### ISSUE TITLE
Link to People tab from other tabs needs to be fixed

### ISSUE THREAD

**Issue by sivaramambikasaran** [RBC-DSAI-IITM/rbc-dsai-iitm.github.io#5]
The link to People's tab from other tabs (except Publications) directs it to a non-existent page. Essentially, the link gets directed to https://rbc-dsai.iitm.ac.in/people instead of https://rbc-dsai.iitm.ac.in/People.

**Comment by DenzilFrancisCrasta** [comment]
Fixed. 
Web-root directory on the production server had a mixture of new and old pages. I have dumped all old content and pushed a fresh copy and verified that all primary-nav links are pointing where they should be.

**Comment by sivaramambikasaran** [comment]
👍🙏
